### ISSUE TITLE
Dependency error: `ReferenceError: self is not defined` for `qr-code-styling`

### ISSUE THREAD

**Issue by kb24x7** [solana-labs/solana-pay#39]
Dependency (`qr-code-styling`) error while trying to use the package in Next.js@12.0.0

![image](https://user-images.githubusercontent.com/61944452/152025668-f2378710-546c-4bd4-82be-fe8f30d2a3d6.png)

```
Server Error

ReferenceError: self is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

It's the same even if I only use the `encodeURL` method.

Linking to a issue and PR for this error in their repository:
https://github.com/kozakdenys/qr-code-styling/issues/38
https://github.com/kozakdenys/qr-code-styling/pull/64

**Comment by jordansexton** [comment]
Thanks for the report, Next.js is really important to support. Do you happen to have a repo that reproduces the issue? Happy to take a look.

**Comment by kb24x7** [comment]
Yeah, just made one: https://github.com/kb24x7/solana-pay-next

**Comment by jordansexton** [comment]
Ah, I see the issue. I had to use this for Jest to run the tests: https://github.com/solana-labs/solana-pay/blob/d7e21ab3da5ac1ed110ba48375e0800a0fc4f8d5/core/jest.config.json#L3

I think the issue is that the QR code library accesses this, https://developer.mozilla.org/en-US/docs/Web/API/Window/self, probably to make UMD build.

While [this workaround](https://github.com/kozakdenys/qr-code-styling/issues/38#issuecomment-1008186177) is an option, disabling SSR is kind of a drag.

If that library is no longer maintained, we should fork it and fix this.

**Comment by jordansexton** [comment]
This is fixed in `@solana/pay@0.1.0-alpha.7`, I tested it with your Next app:
<img width="755" alt="Screen Shot 2022-02-01 at 3 42 14 PM" src="https://user-images.githubusercontent.com/1173161/152056216-f1306522-e181-4c66-bacd-ed224b2f1e7d.png">

**Comment by kb24x7** [comment]
Great! Thanks for the quick fix, actually I did make myself a fork as well 😄

**Comment by zhen1asemen1uk** [comment]
Help please with this problem 😥
I don't see solving

**Comment by zholadev** [comment]
import through next/dynamic
