### ISSUE TITLE
[Error]  Can't import the named export 'blob' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Anmolnoor** [solana-labs/solana-pay#90]
got this error after adding the createQR function and append into the element in document 
``` javascript
import { createQR } from "@solana/pay";

const QRCODE = createQR(res.url);

const element = document.getElementById("QRCODE");

QRCODE.append(element);
```

![image](https://user-images.githubusercontent.com/52135717/154851473-f51322af-bf90-40a4-9861-b8b97af8e2b5.png)

also more in browser 
![image](https://user-images.githubusercontent.com/52135717/154851534-cf19aa1e-4155-4829-aee3-e0124a1eaf1e.png)

**Comment by Anmolnoor** [comment]
After reading this https://github.com/solana-labs/solana-pay/blob/master/core/src/createQR.ts 
I came up with this 
``` javascript
import QRCodeStyling from "@solana/qr-code-styling";
import {createQROptions} from "@solana/pay";

const qr = createQROptions(url);
qrCode = new QRCodeStyling(qr);

```
where QR-code is empty but it works for 1 or 2 times in 100 attempts

**Comment by jordansexton** [comment]
This is most likely not a bug with Solana Pay but an issue with whatever build tool you may be using. It's caused by something not handling ES modules. My guess is that you're using Babel / Webpack, or something based on it, such as CRA / Create React App.

I would recommend using Parcel or Next.js, since they handle these without extra config. If you are set on using CRA, this might help: https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter
